
* VWA - Direkte Analyse von Chlorophyllkataboliten

** Zweck dieses Projekts

Diese Arbeit wurde im Rahmen der österreichischen Reifeprüfung im Zeitraum von 2017 bis Anfang 2018 verfasst. 

** Wie kann die Arbeit angeschaut werden?

Die im Moment des Aufrufes fertige Arbeit befindet sich im Dokument -> main.pdf.

** Inhalte:

- Im Ordner -> /content befinden sich die LaTex Dokumente der einzelnen Kapitel
- Im Ordner -> /figures befinden sich sämtliche für die Arbeit benötigten Graphiken
- Im Ordner -> /template befinden sich alle relevanten Dateien, die für LaTex Pakete, den generelen Style der Arbeit und dergleichen verantwortlich sind

Die Datei -> references-biblatex.bib.blg entält alle verwendeten Quellenangaben.

** Bis zu welchem Zeitpunkt wird an der Arbeit noch gearbeitet?

Bis Mitte Februar wird potentiell noch etwas verändert, da sie erst zu diesem Zeitpunkt abgegeben werden muss.

** License of the template used for compilation with LaTex

This template is licensed under a [[https://creativecommons.org/licenses/by-sa/3.0/][Creative Commons
      Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license]]:

- You can share (to copy, distribute and transmit) this template.
- You can remix (adapt) this template.
- You can make commercial use of the template.
- In case you modify this template and share the derived template: You
  must attribute the template such that you do not remove
  (co-)authorship of Karl Voit and you must not remove the URL to [[https://github.com/novoid/LaTeX-KOMA-template][the
  original repository on github]].
- If you alter, transform, or build a new template upon this template,
  you may distribute the resulting template only under the same or
  similar license to this one.
- There are *no restrictions* of any kind, however, related to the
  resulting (PDF) document!
- You may remove the colophon (but it's not recommended).

Quelle des Templates: "https://github.com/novoid/LaTeX-KOMA-template/"
